### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Xythrion#2]
- [x] a6d11209e5b1857bf42a53486dd343c1f8869dd3: Redo the uptime command so the information is actually useful.
- [ ] Make very simple reminders, with the database.
- [ ] Put links back in database.
- [ ] Find out how to get `.svg`s into embed (if possible, at all).
- [ ] Create custom embeds with formatting.
- [ ] Create lexical analyzer.
- [ ] Use said lexical analyzer for graphing and a simple calculator.
- [ ] Image manipulator by matrices.
- [x] d7469cb77f90c57233db4839b201956167888fe9: Containerize the environment for the bot.
- [ ] Use Azure to redeploy on pushes to master.

**Comment by Xithrius** [comment]
Moved to README roadmap.
