### ISSUE TITLE
Roadmap for the release of v2.0.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/Xythrion#9]
- [ ] Extensions:
    - [x] Administration:
        - [x] Development
        - [x] Warnings
    - [x] Game Data
        - [x] Factorio
        - [x] Warframe
    - [ ] Generation:
        - [ ] Graphing
            - [ ] Single variable expressions
            - [ ] Graphing points
        - [x] Randoms
            - [x] Dice bar graphs
            - [ ] Scatter plots of random points
    - [x] Meta:
        - [x] Links
    - [ ] Requesters
        - [ ] Reddit
            - [x] Upvotes over time
            - [ ] Posts over time
        - [ ] Weather
            - [ ] Mars
            - [ ] Earth
        - [x] Tinyy url shortener
        - [ ] Cryptocurrency graphs
- [ ] Wiki:
     - [ ] Command usage (with images)
- [ ] Hosting:
    - [ ] Auto-redeployment on pushes to master

**Comment by Xithrius** [comment]
Closing to rewrite.
